apiVersion: v1
kind: Pod
metadata:
  name: hpcgame-test-focus
  labels:
    name: hpcgame-test-focus
spec:
  nodeSelector:
    # Node: x86 / gpu
    nvidia.com/gpu.product: NVIDIA-A800-80GB-PCIe-MIG-2g.20gb-SHARED
  containers:
    - name: rdma
      securityContext:
        capabilities:
          add: ["SYS_PTRACE", "IPC_LOCK"]
      # 题目要求cuda这个image
      image: crmirror.lcpu.dev/hpcgame/cuda:latest
      resources:
        limits:
          memory: 12Gi
          cpu: 4
          nvidia.com/gpu: 1
        requests:
          memory: 12Gi
          cpu: 4
          nvidia.com/gpu: 1
      command:
        - sleep
        - inf
