apiVersion: v1
kind: Pod
metadata:
  name: hpcgame-test-compilex
  labels:
    name: hpcgame-test-compilex
  annotations:
    k8s.v1.cni.cncf.io/networks: default/wm2-roce
spec:
  nodeSelector:
    # Intel Xeon 8358
    hpc.lcpu.dev/partition: x86
  containers:
    - name: rdma
      securityContext:
        capabilities:
          add: ["SYS_PTRACE", "IPC_LOCK"]
      image: crmirror.lcpu.dev/hpcgame/intel:latest # 请自行替换
      resources:
        limits:
          memory: 4Gi
          cpu: 1
          rdma.hpc.lcpu.dev/hca_cx5: 1
      command:
        - sleep
        - inf
